travis:
  secure:
    BINSTAR_TOKEN: s6YWQ4C7nebc34oxbE+1X+O8Yi03UApT1sIEcAPkfnyj7m8ZkdUPOE4G5b3oOkzOvTdYZ6BvPfqKPGTW5ihX/8bOTq5cFlsbWIuqyPChw3ZtoYNFhQxDMO3UXUKGNJLkQsLoXxgWMa1VEh3xkNLcsH8KwtizYF/PICzWrjgA6U40SwLne9BLwyykpq3R8/O/XyZsYYuzkBjCEdqPhIicyV8s0ztQO8RBB+Zn8gbH3yX7LvQvGW0vsnxhQll/HgZfS+WuGB2oPsei9yxCRrOHMoGa/L2VaemMBPLLl/v2aSThkyIIWyxQmZ9gifxdBgL6oVYY3/8vuATkMleG6GZkEwA6i1kezaqjNoHMxMunBxdx4uW4GKE8ouuV59ghpamjNVHBqTeTc1SISz16yPPrzrng3o6/gEfkv/jzRKOduPbiRD5BCjVfCWnvVc+5VqQgfQ0Nrhymq3B0tA5XkDwK/8knssjkuwNMAydG9hNlJbT18FAek6bIB9uiwguGR8nqbMBiBDXrd0Alv84bc5Bf8hV//DJJosZaBgsb8Xj7k56tBmu/xLze4g2yE+tOsH4lnaXJbO4cNNWEfZvHI3BltISqczqARKelN5m7FB142ZNR4UGtQNb3vNGaP4vByRc4m25UnJ7Ijr3QqhA36UPEuV6h/udBXsKkm3OzBcEsiqA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
